### ISSUE TITLE
Question about robot jumping in rviz

### ISSUE THREAD

**Issue by sbetts2** [Htet-Wai-Yan-HWY/loc_diff#1]
Hi, I am new to Nav2 and this repository has been a great help trying to get nav2 to work in humble.

However, when I run ros2 launch rlnav2 gps_waypoint_follower.launch.py it doesn't move, isn't it supposed to follow a set of waypoints? Selecting Nav2 goal makes the robot move, but then if i restart the gps_waypoint_follower.launch.py then my robot in rviz starts to jump around on the screen. What is the reason for this?

![image](https://github.com/gyiptgyipt/loc_diff/assets/32182992/1d28e9d4-8821-44e1-941b-1c7d011134a3)

![image](https://github.com/gyiptgyipt/loc_diff/assets/32182992/d2b7ea44-c9c5-4a97-b468-c8c9013e9edd)

![image](https://github.com/gyiptgyipt/loc_diff/assets/32182992/cf5f0aeb-5ed3-423b-b112-848b401e0d66)

**Comment by gyiptgyipt** [comment]
Hello, 

Thanks for this report and question. The gps_waypoint_follower.launch.py need to update to work (not finish yet)because I took it directly from nav2_tutorials wrote for iron version. 

and the reason that robot jumping in rviz is the configuration of odometry in rlnav2/config/test.yaml  and robot is subscribing from two odom sources.

This is my repository's fault and I will let you know when I am done.

**Comment by sbetts2** [comment]
Ok, Thanks for the update.

**Comment by gyiptgyipt** [comment]
robot jumping arround fixed (but need to tune robot localization and nav2) 
- to add gps_waypoint follower
